spring.application.name=assignment-system
server.port=8080

spring.data.mongodb.uri=mongodb+srv://namithshetty01_db_user:FGOm40RlUmNNUlI1@dascluster.2dzbsy9.mongodb.net/assignmentDB?retryWrites=true&w=majority

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

app.jwt.secret=VGhpcy1pcy1hLXNlY3VyZS1iYXNlNjQtc2VjcmV0LWZvci1kaWdpdGFsLWFzc2lnbm1lbnQtc3lzdGVt
app.jwt.expiration-ms=86400000
app.upload.dir=uploads

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

server.error.include-message=always
server.error.include-binding-errors=always